<?php
return array(
	'HTTP_CACHE_CONTROL' => 'no-cache,must-revalidate',
	//'配置项'=>'配置值'
	'URL_CASE_INSENSITIVE' => true,
	'URL_MODEL' => 0,
	'DB_TYPE' => 'mysql',
	'DB_HOST' => '127.0.0.1',
	'DB_NAME' => 'info',
	'DB_USER' => 'root',
	'DB_PWD' => 'sgb!@#',
//	'DB_USER' => 'mengjun',
//	'DB_PWD' => 'sa',
	'DB_PORT' => '3306',
	'DB_PREFIX' => 'info_',
	'DB_CHARSET' => 'utf8',
//	'BASE_URI'	=> '/',
	'BASE_URI'	=> '/info/',
	'IP_DATA_DIR'=> __DIR__.'/wry.dat',
	'ZDING_NUM' => 5,
	//积分相关规则
	'JIFEN_POST_DEC' => 10,
	'JIFEN_POST_PIC_DEC' => 10,
	'JIFEN_REFRESH_DEC' => 5,
	'JIFEN_ZDING_XIAO'=>20,
	'JIFEN_ZDING_DA'=>30,
	'JIFEN_ZDING_ALL'=>50,
	'JIFEN_SIGN_INC' => 10,
	'JIFEN_COMMENT_INC' => 1,

	//国际化相关KEY
	'LANG' => array(
		'sentence'=>array(
			'send_mail_detail_tip'=>'给 %s 发送站内信，方便又省钱',
			'had_signed_tips'=>'已经签到过',
			'user_not_login_tips'=>'用户未登录',
			'edit_not_exists'=>'编辑的信息不存在',
			'no_permission'=>'权限不足',
			'no_enough_refresh_score'=> '积分不足，刷新最少 %d 分',
			'no_enough_pub_score'=>'积分不足，发帖最少 %d 分',
			'no_enouth_zding_score'=>'积分不足，置顶最少 %d 分',
			'no_enough_pub_pic_score'=>'积分不足,发送有图信息至少需要 %d 分',
			'zding_days_error_tips'=>'请输入大于等于1的指定天数',
		),
		'term' => array(
			//头部
			'shouye'=>'首页',
			'chengshi'=>'城市',
			'dangqianchengshi'=>'当前城市',
			'suoyou'=>'所有',
			'zhuce'=>'注册',
			'yonghuming'=> '用户名',
			'shoujihao'=>'手机号',
			'mima'=>'密码',
			'guanbi'=>'关闭',
			'denglu'=>'登录',
			'zhanghao'=>'账号',
			'tuich'=>'退出',
			'qingshuru'=>'请输入',
			'jizhuwo'=>'记住我',
			'jifen'=>'积分',
			'qiandao'=>'签到',
			'mianfeifabuxinxi'=>'免费发布信息',
			'gerenzhongxin'=>'个人中心',
			'tuichudenglu'=>'退出登录',
			'querenmima'=>'确认密码',
			'qiehuanyuyan'=>'切换英文',
			//首页
			'zhaopin'=>'招聘',
			'chazhao'=>'查找',
			'shaixuan'=>'筛选',
			'quanbuchengshi'=>'全部城市',
			'zanzhushanglianjie'=>'赞助商链接',
			'zuixinxinxi'=>'最新信息',
			'zhidingtie'=>'置顶帖',
			//详情页
			'fasong'=>'发送',
			'zhanneixin'=>'站内信',
			'shoujianren'=>'收件人',
			'lianxiren'=>'联系人',
			'dianhua'=>'电话',
			'xiangqing'=>'详情',
			'gongsi'=>'公司',
			'rixin'=>'日薪',
			'quyu'=>'区域',
			'riqi'=>'日期',
			'liulan'=>'浏览',
			'dizhijiguishudi'=>'地址及归属地',
			//发布页
			'biaoti'=>'标题',
			'fenlei'=>'分类',
			'xuanzexinxileimu'=>'选择信息类目',
			'gongzi'=>'工资',
			'gongsimingcheng'=>'公司名称',
			'miaoshu'=>'描述',
			'shangchuanzhaopian'=>'上传照片',
			'gongzuodidian'=>'工作地点',
			'xuanzechengshi'=>'选择城市',
			'xiangxidizhi'=>'详细地址',
			'zaiditushangbiaozhu'=>'在地图上标注',
			'lianxidianhua'=>'联系电话',
			'fabu'=>'发布',
			'quxiao'=>'取消',
			'biaozhuweizhi'=>'标注位置',
			'dangqianbiaozhuweizhi'=>'当前标注位置',
			'queding'=>'确定',
			'xiugai'=>'修改',
			//用户中心
			'wodefabu'=>'我的发布',
			'wodesixin'=>'我的私信',
			'shijian'=>'时间',
			'leibie'=>'类别',
			'caozuo'=>'操作',
			'shuaxin'=>'刷新',
			'shanchu'=>'删除',
			'zhidingleixing'=>'置顶类型',
			'xiaolei'=>'小类',
			'dalei'=>'大类',
			'quanzhan'=>'全站',
			'zhidingshijian'=>'置顶时间',
			'tianshu'=>'天数',
			'zhiding'=>'置顶',

			//私信
			'gengduoxiaoxi'=>'更多消息',
			'yonghu'=>'用户',
			'shuo'=>'说',
			'huifu'=>'回复',
			//action
			'chenggong'=>'成功',
			'shibai'=>'失败',
			'cuowu'=>'错误',
			'qingxiandenglu'=>'请先登录',
			'xieru'=>'写入',

		)
	),

	'LANG-EN' => array(
		'sentence'=>array(
			'send_mail_detail_tip'=>'send message to %s so easy!',
			'had_signed_tips'=>'you has signed today',
			'user_not_login_tips'=>'user not login',
			'edit_not_exists'=>'your edit not exists',
			'no_permission'=>'permission deny',
			'no_enough_refresh_score'=> 'you have not engouth score to refreash,you need %d score',
			'no_enough_pub_score'=>'you have not engouth score to publish,you need %d score',
			'no_enough_pub_pic_score'=>'you have not engouth score to publish whith a photo,you need %d score',
		),
		'term' => array(
			//头部
			'shouye'=>'homepage',
			'chengshi'=>'city',
			'dangqianchengshi'=>'current city',
			'suoyou'=>'ALL',
			'zhuce'=>'register',
			'yonghuming'=> 'username',
			'shoujihao'=>'phone',
			'mima'=>'password',
			'guanbi'=>'close',
			'denglu'=>'login',
			'zhanghao'=>'account',
			'tuich'=>'logout',
			'qingshuru'=>'please input ',
			'jizhuwo'=>'remember',
			'jifen'=>'score',
			'qiandao'=>'sign today',
			'mianfeifabuxinxi'=>'free publish an info',
			'gerenzhongxin'=>'user center',
			'tuichudenglu'=>'logout',
			'querenmima'=>'confirm password',
			'qiehuanyuyan'=>'chang language chinese',
			//首页
			'zhaopin'=>'jobs',
			'chazhao'=>'search',
			'shaixuan'=>'falter',
			'quanbuchengshi'=>'ALL',
			'zanzhushanglianjie'=>'ads links',
			'zuixinxinxi'=>'newest info',
			//详情页
			'fasong'=>'send',
			'zhanneixin'=>'mail in web',
			'shoujianren'=>'to',
			'lianxiren'=>'contract',
			'dianhua'=>'phone',
			'xiangqing'=>'detail',
			'gongsi'=>'company',
			'rixin'=>'pay per day',
			'quyu'=>'region',
			'riqi'=>'date',
			'liulan'=>'views',
			'dizhijiguishudi'=>' and ip located address',
			//发布页
			'biaoti'=>'title',
			'fenlei'=>'category',
			'xuanzexinxileimu'=>'choose a category',
			'gongzi'=>'pay',
			'gongsimingcheng'=>'company',
			'miaoshu'=>'describe',
			'shangchuanzhaopian'=>'upload photo',
			'gongzuodidian'=>'working place',
			'xuanzechengshi'=>'choose a city',
			'xiangxidizhi'=>'detial address',
			'zaiditushangbiaozhu'=>'mark on map',
			'lianxidianhua'=>'contract phone',
			'fabu'=>'submit',
			'quxiao'=>'cancle',
			'biaozhuweizhi'=>'mark position',
			'dangqianbiaozhuweizhi'=>'current mark position',
			'queding'=>'ok',
			'xiugai'=>'edit',
			//用户中心
			'wodefabu'=>'my publish',
			'wodesixin'=>'my mail',
			'shijian'=>'date',
			'leibie'=>'category',
			'caozuo'=>'action',
			'shuaxin'=>'refresh',
			'shanchu'=>'remove',
			//私信
			'gengduoxiaoxi'=>'more mails',
			'yonghu'=>'user',
			'shuo'=>'says',
			'huifu'=>'re',
			//action
			'chenggong'=>'success',
			'shibai'=>'failed',
			'cuowu'=>'error',
			'qingxiandenglu'=>'pleash login',
			'xieru'=>'write',
		)
	)

);
?>
